#!/usr/bin/env python3
# Rasterize a monospace font into a compact 1-bpp bitmap table (ASCII 32..126)
# for the nvmmdrawdet overlay. Emits a C array: W columns x H rows per glyph,
# stored row-major as bytes (one byte per row, LSB = leftmost column).
# Cell chosen so W<=8 (fits one byte per row).
import sys
try:
    from PIL import Image, ImageFont, ImageDraw
except Exception as e:
    print("NO_PIL:%s" % e); sys.exit(2)

CW, CH = 6, 8          # glyph cell: 6 wide (fits a byte), 8 tall
candidates = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
]
font = None
for path in candidates:
    try:
        font = ImageFont.truetype(path, 8); break
    except Exception:
        continue
if font is None:
    print("NO_FONT"); sys.exit(3)

rows = []
for code in range(32, 127):
    img = Image.new("L", (CW, CH), 0)
    d = ImageDraw.Draw(img)
    d.text((0, -1), chr(code), fill=255, font=font)
    glyph = []
    for y in range(CH):
        bits = 0
        for x in range(CW):
            if img.getpixel((x, y)) > 96:
                bits |= (1 << x)
        glyph.append(bits)
    rows.append((code, glyph))

print("#pragma once")
print("// Generated by tools/gen_font.py from DejaVuSansMono 8px — do not edit.")
print("// ASCII 32..126, %dx%d cell, 1 byte/row (LSB=leftmost column)." % (CW, CH))
print("static const unsigned char FONT_W = %d, FONT_H = %d;" % (CW, CH))
print("static const unsigned char FONT_FIRST = 32, FONT_LAST = 126;")
print("static const unsigned char kFont[%d][%d] = {" % (len(rows), CH))
for code, glyph in rows:
    body = ",".join("0x%02x" % b for b in glyph)
    print("    {%s}, // %d '%s'" % (body, code, chr(code) if code != 32 else " "))
print("};")
